language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

before_script:
  - composer selfupdate
  - composer install --dev
  - echo 'extension = "zmq.so"' > /tmp/zmq.conf 
  - php-env config-add zmq.conf
  - wget https://scrutinizer-ci.com/ocular.phar

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover
  - vendor/bin/phpcs --standard=./phpcs.xml -n --report=gitblame ./src
  - vendor/bin/bugfree lint src/
  - if [ $(phpenv version-name) = '5.6' ]; then wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

notifications:
  webhooks:
    urls:
      - http://satisio.us/repositories/buildhook/
    on_success: always
    on_failure: always
    on_start: true
